---
title: "Data Processing"
author: "Wei-Lun, Lin"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
dat <- read_rds("../1-raw/nbh_clean_conjoint_global.rds")
```

## Potential Profiles

There are 5 attributes, all the potential profiles should be listed.

```{r}
library(tidyverse)

profiles <- with(
  dat,
  expand.grid(
   vulnerability = unique(vulnerability),
   transmission = unique(transmission),
   income = unique(income),
   occupation = unique(occupation),
   age_category = unique(age_category)
  )
) %>% 
  mutate(index = 1:864, .before=1)

str(profiles)
```

save the profiles

```{r}
write_rds(profiles, "../2-processed/CANDOUR_profiles.rds")
```


## Data

Index of trials and profiles should be added to the data.

```{r}
dat <- dat %>% 
  left_join(
    profiles,
    by = colnames(profiles)[-1]
  ) %>% 
  mutate(trial_id = ceiling(row_number() / 2)) %>% 
  rename(profile_id = index)
head(dat)
```

save the edited global data

```{r}
write_rds(dat, "../2-processed/CANDOUR_data.rds")
```

